// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecommerce.Data.Access.DAL;

namespace ecommerce.Data.Access.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20210214053122_seed_options_vehicles_customer_data")]
    partial class seed_options_vehicles_customer_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ecommerce.Data.Model.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AnnualIncome")
                        .HasColumnType("float");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLegalEntity")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("ManufacturerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("StockInHand")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251445"),
                            Address = "New Land, Car Street 900",
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 786, DateTimeKind.Local).AddTicks(9281),
                            CreateUserId = "System",
                            ManufacturerName = "Volivo Motors",
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 786, DateTimeKind.Local).AddTicks(9344),
                            ModifyUserId = "System",
                            StatusId = 1,
                            StockInHand = 99,
                            Telephone = "01401245122",
                            Type = "Main Office"
                        },
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251235"),
                            Address = "New Land, Factory street",
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 786, DateTimeKind.Local).AddTicks(9546),
                            CreateUserId = "System",
                            ManufacturerName = "Volivo Factory 1",
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 786, DateTimeKind.Local).AddTicks(9590),
                            ModifyUserId = "System",
                            StatusId = 1,
                            StockInHand = 99,
                            Telephone = "01245487541",
                            Type = "Factory"
                        },
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237261335"),
                            Address = "New Land, Factory street 2",
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 786, DateTimeKind.Local).AddTicks(9687),
                            CreateUserId = "System",
                            ManufacturerName = "Volivo Factory 2",
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 786, DateTimeKind.Local).AddTicks(9729),
                            ModifyUserId = "System",
                            StatusId = 1,
                            StockInHand = 99,
                            Telephone = "01401245122",
                            Type = "Factory"
                        },
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc3237251336"),
                            Address = "New Land, Warehouse Street 900",
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 786, DateTimeKind.Local).AddTicks(9900),
                            CreateUserId = "System",
                            ManufacturerName = "Volivo Warehouse",
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 786, DateTimeKind.Local).AddTicks(9942),
                            ModifyUserId = "System",
                            StatusId = 1,
                            StockInHand = 99,
                            Telephone = "01401245122",
                            Type = "WareHouse"
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.OptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("ManufacturerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("QtyStock")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerEntityId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ENG-COMP",
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 788, DateTimeKind.Local).AddTicks(1156),
                            CreateUserId = "System",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251235"),
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 788, DateTimeKind.Local).AddTicks(1223),
                            ModifyUserId = "System",
                            Name = "Engine",
                            Price = 9000.0,
                            QtyStock = 10,
                            StatusId = 1,
                            Value = "V12 Engine"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CHA-COMP",
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 788, DateTimeKind.Local).AddTicks(1398),
                            CreateUserId = "System",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237261335"),
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 788, DateTimeKind.Local).AddTicks(1440),
                            ModifyUserId = "System",
                            Name = "Chasis",
                            Price = 10000.0,
                            QtyStock = 10,
                            StatusId = 1,
                            Value = "Ladder Frame"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OPT-COMP",
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 788, DateTimeKind.Local).AddTicks(1517),
                            CreateUserId = "System",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237261335"),
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 788, DateTimeKind.Local).AddTicks(1558),
                            ModifyUserId = "System",
                            Name = "Option Pack",
                            Price = 5000.0,
                            QtyStock = 10,
                            StatusId = 1,
                            Value = "Performance Package"
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 568, DateTimeKind.Local).AddTicks(7603),
                            CreateUserId = "System",
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 571, DateTimeKind.Local).AddTicks(5867),
                            ModifyUserId = "System",
                            RoleName = "Admin",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 571, DateTimeKind.Local).AddTicks(9442),
                            CreateUserId = "System",
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 571, DateTimeKind.Local).AddTicks(9487),
                            ModifyUserId = "System",
                            RoleName = "Manufacturer",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 571, DateTimeKind.Local).AddTicks(9540),
                            CreateUserId = "System",
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 571, DateTimeKind.Local).AddTicks(9542),
                            ModifyUserId = "System",
                            RoleName = "Customer",
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.StatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerEntityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251335"),
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 784, DateTimeKind.Local).AddTicks(8490),
                            CreateUserId = "System",
                            Email = "admin@mail.com",
                            FirstName = "john",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251445"),
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 785, DateTimeKind.Local).AddTicks(163),
                            ModifyUserId = "System",
                            Password = "$2a$11$XP/bBuCSIZTI/avsGFwu3.bixGANw5gidl88Bw/WHAIY/lndJBZm.",
                            StatusId = 1,
                            Surname = "Doe"
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.UserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("RoleEntityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleEntityId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 2, 14, 7, 31, 21, 785, DateTimeKind.Local).AddTicks(8928),
                            CreateUserId = "System",
                            ModifyDate = new DateTime(2021, 2, 14, 7, 31, 21, 785, DateTimeKind.Local).AddTicks(8992),
                            ModifyUserId = "System",
                            RoleEntityId = 1,
                            StatusId = 1,
                            UserEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251335")
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("ManufacturerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerEntityId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.VehicleOptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("OptionEntityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("VehicleOptions");
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.OptionEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.UserEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecommerce.Data.Model.Entities.UserEntity", "UserEntity")
                        .WithMany("Roles")
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.VehicleEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
