// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecommerce.Data.Access.DAL;

namespace ecommerce.Data.Access.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20210214142831_add_vehicle_seed_data")]
    partial class add_vehicle_seed_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ecommerce.Data.Model.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AnnualIncome")
                        .HasColumnType("float");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLegalEntity")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff5641f7-ce8d-4de5-aef7-bc4213251566"),
                            Address = "Randpark Ridge, House street",
                            AnnualIncome = 900000.0,
                            City = "Johannesburg",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "freedom.khanyile@mail.com",
                            FirstName = "Freedom",
                            IsLegalEntity = false,
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "07455658457",
                            StatusId = 0,
                            Surname = "Khanyile"
                        },
                        new
                        {
                            Id = new Guid("ff5641f7-ce8d-4de5-aef7-bc4213251586"),
                            Address = "Mine park, Mines street",
                            AnnualIncome = 90000000.0,
                            City = "Johannesburg",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@goldman-mines.com",
                            FirstName = "Goldman Mines",
                            IsLegalEntity = true,
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0112457854",
                            StatusId = 0
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("ManufacturerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("StockInHand")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251445"),
                            Address = "New Land, Car Street 900",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 66, DateTimeKind.Local).AddTicks(3059),
                            CreateUserId = "System",
                            ManufacturerName = "Volivo Motors",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 66, DateTimeKind.Local).AddTicks(3069),
                            ModifyUserId = "System",
                            StatusId = 1,
                            StockInHand = 99,
                            Telephone = "01401245122",
                            Type = "Main Office"
                        },
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251235"),
                            Address = "New Land, Factory street",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 66, DateTimeKind.Local).AddTicks(3184),
                            CreateUserId = "System",
                            ManufacturerName = "Volivo Factory 1",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 66, DateTimeKind.Local).AddTicks(3186),
                            ModifyUserId = "System",
                            StatusId = 1,
                            StockInHand = 99,
                            Telephone = "01245487541",
                            Type = "Factory"
                        },
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237261335"),
                            Address = "New Land, Factory street 2",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 66, DateTimeKind.Local).AddTicks(3192),
                            CreateUserId = "System",
                            ManufacturerName = "Volivo Factory 2",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 66, DateTimeKind.Local).AddTicks(3193),
                            ModifyUserId = "System",
                            StatusId = 1,
                            StockInHand = 99,
                            Telephone = "01401245122",
                            Type = "Factory"
                        },
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc3237251336"),
                            Address = "New Land, Warehouse Street 900",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 66, DateTimeKind.Local).AddTicks(3197),
                            CreateUserId = "System",
                            ManufacturerName = "Volivo Warehouse",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 66, DateTimeKind.Local).AddTicks(3198),
                            ModifyUserId = "System",
                            StatusId = 1,
                            StockInHand = 99,
                            Telephone = "01401245122",
                            Type = "WareHouse"
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.OptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("ManufacturerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("QtyStock")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerEntityId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ENG-COMP",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(1225),
                            CreateUserId = "System",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251235"),
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(1236),
                            ModifyUserId = "System",
                            Name = "Engine",
                            Price = 9000.0,
                            QtyStock = 10,
                            StatusId = 1,
                            Value = "V12 Engine"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CHA-COMP",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(1306),
                            CreateUserId = "System",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237261335"),
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(1307),
                            ModifyUserId = "System",
                            Name = "Chasis",
                            Price = 10000.0,
                            QtyStock = 10,
                            StatusId = 1,
                            Value = "Ladder Frame"
                        },
                        new
                        {
                            Id = 3,
                            Code = "OPT-COMP",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(1311),
                            CreateUserId = "System",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237261335"),
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(1313),
                            ModifyUserId = "System",
                            Name = "Option Pack",
                            Price = 5000.0,
                            QtyStock = 10,
                            StatusId = 1,
                            Value = "Performance Package"
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("CustomerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerEntityId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.OrderLineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("IsAssembling")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("OrderEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderEntityId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 30, 888, DateTimeKind.Local).AddTicks(5326),
                            CreateUserId = "System",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 30, 890, DateTimeKind.Local).AddTicks(4470),
                            ModifyUserId = "System",
                            RoleName = "Admin",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 30, 890, DateTimeKind.Local).AddTicks(6328),
                            CreateUserId = "System",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 30, 890, DateTimeKind.Local).AddTicks(6351),
                            ModifyUserId = "System",
                            RoleName = "Manufacturer",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 30, 890, DateTimeKind.Local).AddTicks(6385),
                            CreateUserId = "System",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 30, 890, DateTimeKind.Local).AddTicks(6387),
                            ModifyUserId = "System",
                            RoleName = "Customer",
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.StatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerEntityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251335"),
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 64, DateTimeKind.Local).AddTicks(7702),
                            CreateUserId = "System",
                            Email = "admin@mail.com",
                            FirstName = "john",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251445"),
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 64, DateTimeKind.Local).AddTicks(9194),
                            ModifyUserId = "System",
                            Password = "$2a$11$zT0N8cYrZnX65rUdkNN.jOpy2sZ4kZ7WfX6bGBiBjwvmy18asWp3u",
                            StatusId = 1,
                            Surname = "Doe"
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.UserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("RoleEntityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleEntityId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 65, DateTimeKind.Local).AddTicks(5263),
                            CreateUserId = "System",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 65, DateTimeKind.Local).AddTicks(5274),
                            ModifyUserId = "System",
                            RoleEntityId = 1,
                            StatusId = 1,
                            UserEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251335")
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("ManufacturerEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerEntityId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251555"),
                            BodyStyle = "Hot Hatchback",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(8006),
                            CreateUserId = "System",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251445"),
                            ModelName = "VW Golf GTI 7",
                            ModelYear = "2021",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(8017),
                            ModifyUserId = "System",
                            StatusId = 1
                        },
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251566"),
                            BodyStyle = "Sedan",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(8081),
                            CreateUserId = "System",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251445"),
                            ModelName = "BMW M3",
                            ModelYear = "2021",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(8083),
                            ModifyUserId = "System",
                            StatusId = 1
                        },
                        new
                        {
                            Id = new Guid("c6e641f7-ce8d-4de5-aef7-bc4213251566"),
                            BodyStyle = "Coupe",
                            CreateDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(8088),
                            CreateUserId = "System",
                            ManufacturerEntityId = new Guid("c6e641f7-ce8d-4de5-aef7-bc4237251445"),
                            ModelName = "Mercedes Benz C63 AMG",
                            ModelYear = "2021",
                            ModifyDate = new DateTime(2021, 2, 14, 16, 28, 31, 67, DateTimeKind.Local).AddTicks(8089),
                            ModifyUserId = "System",
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.VehicleOptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("OptionEntityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("VehicleOptions");
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.OptionEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.OrderEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.OrderLineEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.OrderEntity", "Order")
                        .WithMany()
                        .HasForeignKey("OrderEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.UserEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecommerce.Data.Model.Entities.UserEntity", "UserEntity")
                        .WithMany("Roles")
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecommerce.Data.Model.Entities.VehicleEntity", b =>
                {
                    b.HasOne("ecommerce.Data.Model.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
